version: '3'
services:
  meu-app-online-store:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online-store-microservice
    image: online-store:1.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./database/database-file:/app/database/database-file
      - ./log/logs-files:/app/log/logs-files
    environment:
      - API_TITLE=Online Store
      - VERSION=1.0.0
      - SECRET_KEY=Advanced Backend Development
      - PORT=5000
      - HOST=0.0.0.0
      - TZ=America/Sao_Paulo
    networks:
      - puc-microservice

networks:
  puc-microservice:
    external: true
